### ISSUE TITLE
Chapter directories are out of sync

### ISSUE THREAD

**Issue by starksm64** [PacktPublishing/Hands-On-Enterprise-Java-Microservices-with-Eclipse-MicroProfile#2]
The health check and jwt code are discussed in chapter 4, "MicroProfile Health Check and JWT Propagation". Right now we have health check in Chapter04-metricsandhc and jwt in Chapter05-jwtpropandot. These need to be renamed to:

Chapter04-jwtpropandhc
Chapter05-metricsandot

**Comment by cealsair** [comment]
Chapters have been separated by specific MP API and are all in-synch now. Does this issue still apply?

**Comment by gaurav-packt** [comment]
Thanks for sharing the feedback. It will surely assist the readers to resolve any issue if they face it.
