### ISSUE TITLE
Use consistent groupIds/packages

### ISSUE THREAD

**Issue by pavolloffay** [PacktPublishing/Hands-On-Enterprise-Java-Microservices-with-Eclipse-MicroProfile#5]
Java classes are packaged under `io.pckt.*` however in `pom.xml` we are using `io.microprofile`. It would be good to unify them.

We should also consider renaming to `com.packt.*` as there is no `io.pckt.*`

**Comment by cealsair** [comment]
@pilhuhn @starksm64 WDYT?
